export const INITIAL_VALUES = {
  active: undefined,
  round: undefined,
  participants: [],
  reorder: false,
};

export const PART_TEMPLATE = {
  id: 1,
  name: 'UNKNOWN',
  type: '',
  initiative: 0,
  status: 'alive',
  conditions: [],
};

export const CONDITIONS = [
  {
    id: 'c7a1e87d-1f2a-4c98-94c3-bd9f12f89101',
    name: 'Slowed',
    type: 'bad',
    value: 1,
    hint: "When you regain your actions, reduce the number of actions regained by your slowed value. Because you regain actions at the start of your turn, you don't immediately lose actions if you become slowed during your turn.",
  },
  {
    id: '8b93d440-bc25-4cf6-9a4b-4af64b67f7a2',
    name: 'Stunned',
    type: 'bad',
    value: 1,
    hint: 'Each time you regain actions, reduce the number you regain by your stunned value, then reduce your stunned value by the number of actions you lost. For example, if you were stunned 4, you would lose all 3 of your actions on your turn, reducing you to stunned 1; on your next turn, you would lose 1 more action, and then be able to use your remaining 2 actions normally. Stunned might also have a duration instead, such as “stunned for 1 minute,” causing you to lose all your actions for the duration.',
  },
  {
    id: 'f2c9f016-8db0-4d20-93a7-73500d5e2b0c',
    name: 'Grabbed',
    type: 'bad',
    value: null,
    hint: "You're held in place by another creature, giving you the off-guard and immobilized conditions. If you attempt a manipulate action while grabbed, you must succeed at a DC 5 flat check or it is lost; roll the check after spending the action, but before any effects are applied.",
  },
  {
    id: '41f6a91b-9d9e-42c2-9bb0-9e80db3df799',
    name: 'Pinned',
    type: 'bad',
    value: null,
    hint: "The target is immobilized and must spend an Interact action to attempt a DC 10 Athletics check to pull the missile free; it can't move from its space until it succeeds. The creature doesn't become stuck if it is incorporeal, is liquid, or could escape without effort.",
  },
  {
    id: '6c2e2e8e-0b16-4d38-8d6f-0e601fb197f6',
    name: 'Wounded',
    type: 'bad',
    value: 1,
    hint: "Anytime you lose the dying condition, you become wounded 1 if you didn't already have the wounded condition. If you already have the wounded condition, your wounded condition value instead increases by 1. If you gain the dying condition while wounded, increase the dying condition’s value by your wounded value. The wounded condition ends if someone successfully restores Hit Points to you with Treat Wounds, or if you are restored to full Hit Points and rest for 10 minutes.",
  },
  {
    id: '3f6e2d9a-1c47-4a6b-9f32-6c1a0d7e5b84',
    name: 'Dying',
    type: 'bad',
    value: 1,
    hint: "You’re unconscious while you have the dying condition. Dying always includes a value. If this value ever reaches dying 4, you die. While you're dying, attempt a recovery check at the start of each of your turns. This is a flat check with a DC equal to 10 + your current dying value to see if you get better or worse. If you take damage while you already have the dying condition, increase your dying condition value by 1, or by 2 if the damage came from an attacker’s critical hit or your own critical failure.",
  },
  {
    id: 'a8d1c4f2-5b3e-4d91-b7a0-1f2e9c8d3a66',
    name: 'Unconscious',
    type: 'bad',
    value: null,
    hint: "You're sleeping, or you've been knocked out. You can't act. You take a -4 status penalty to AC, Perception, and Reflex saves, and you have the blinded and off-guard conditions. When you gain this condition, you fall prone and drop items you're wielding or holding unless the effect states otherwise or the GM determines you're in a position in which you wouldn't.",
  },
  {
    id: '7a541eb9-1688-4de8-a18f-356746df8cf3',
    name: 'Doomed',
    type: 'bad',
    value: 1,
    hint: "The dying value at which you die is reduced by your doomed value. If your maximum dying value is reduced to 0, you instantly die. When you die, you're no longer doomed. Your doomed value decreases by 1 each time you get a full night's rest.",
  },
  {
    id: 'b3b981cb-33e7-468b-9e44-5c2f7f6c403f',
    name: 'Clumsy',
    type: 'bad',
    value: 1,
    hint: 'You take a status penalty equal to the condition value to Dexterity-based rolls and DCs, including AC, Reflex saves, ranged attack rolls, and skill checks using Acrobatics, Stealth, and Thievery.',
  },
  {
    id: 'c4a8f947-4c9b-4d37-bb1a-69d0a76c5370',
    name: 'Drained',
    type: 'bad',
    value: 1,
    hint: "You take a status penalty equal to your drained value on Constitution-based rolls and DCs, such as Fortitude saves. You also lose a number of Hit Points equal to your level (minimum 1) times the drained value, and your maximum Hit Points are reduced by the same amount. Each time you get a full night's rest, your drained value decreases by 1. This increases your maximum Hit Points, but you don't immediately recover the lost Hit Points.",
  },
  {
    id: '3b2b9d59-9a0f-4823-b1b6-cc4d12a944a9',
    name: 'Enfeebled',
    type: 'bad',
    value: 1,
    hint: 'When you are enfeebled, you take a status penalty equal to the condition value to Strength-based rolls and DCs, including Strength-based melee attack rolls, Strength-based damage rolls, and Athletics checks.',
  },
  {
    id: '9e75f208-9d7b-4e3b-9d8e-4f0af9a18d25',
    name: 'Stupified',
    type: 'bad',
    value: 1,
    hint: 'You take a status penalty equal to this value on Intelligence-, Wisdom-, and Charisma-based rolls and DCs, including Will saving throws, spell attack modifiers, spell DCs, and skill checks that use these attribute modifiers. Any time you attempt to Cast a Spell while stupefied, the spell is disrupted unless you succeed at a flat check with a DC equal to 5 + your stupefied value.',
  },
  {
    id: 'df9df631-4b74-4f83-9bfb-5e01c5e6b0b8',
    name: 'Blinded',
    type: 'bad',
    value: null,
    hint: "You can't see. All normal terrain is difficult terrain to you. You can't detect anything using vision. You automatically critically fail Perception checks that require you to be able to see, and if vision is your only precise sense, you take a -4 status penalty to Perception checks. You are immune to visual effects. Blinded overrides dazzled.",
  },
  {
    id: 'fae7b2c7-4c73-44a3-9545-9012194f9342',
    name: 'Dazzled',
    type: 'bad',
    value: null,
    hint: 'If vision is your only precise sense, all creatures and objects are concealed from you.',
  },
  {
    id: '7b0a89d3-2f2f-45a0-b09e-2ff0df2b2871',
    name: 'Deafened',
    type: 'bad',
    value: null,
    hint: 'You automatically critically fail Perception checks that require you to be able to hear. You take a -2 status penalty to Perception checks for initiative and checks that involve sound but also rely on other senses. If you perform an action that has the auditory trait, you must succeed at a DC 5 flat check or the action is lost; attempt the check after spending the action but before any effects are applied. You are immune to auditory effects while deafened.',
  },
  {
    id: '52c1e820-b7cf-44ad-8b7f-55c5d0c35c09',
    name: 'Confused',
    type: 'bad',
    value: null,
    hint: "You are off-guard, you don't treat anyone as your ally (though they might still treat you as theirs), and you can't Delay, Ready, or use reactions. You use all your actions to Strike or cast offensive cantrips, though the GM can have you use other actions to facilitate attack, such as draw a weapon, move so target is in reach, and so forth. Your targets are determined randomly by the GM. If you have no other viable targets, you target yourself, automatically hitting but not scoring a critical hit. If it's impossible for you to attack or cast spells, you babble incoherently, wasting your actions. Each time you take damage from an attack or spell, you can attempt a DC 11 flat check to recover from your confusion and end the condition.",
  },
  {
    id: '6e514d13-3024-4d83-a9d1-bf0ab9e3f2a1',
    name: 'Silenced',
    type: 'good',
    value: null,
    hint: "The target makes no sound, preventing creatures from noticing it using hearing alone. The target can't use sonic attacks, nor can it use auditory actions. This also prevents the target from casting spells due to the magical words involved in casting, with the exception of subtle spells.",
  },
  {
    id: '59d20854-6b3b-4d47-857f-3c0af207a39a',
    name: 'Controlled',
    type: 'bad',
    value: null,
    hint: "The controller dictates how you act and can make you use any of your actions, including attacks, reactions, or even Delay. The controller usually doesn't have to spend their own actions when controlling you.",
  },
  {
    id: 'b1de937f-b7d8-4f5c-93a6-50f20ad1433c',
    name: 'Fascinated',
    type: 'bad',
    value: null,
    hint: "You take a -2 status penalty to Perception and skill checks, and you can't use concentrate actions unless they (or their intended consequences) are related to the subject of your fascination, as determined by the GM. For instance, you might be able to Seek and Recall Knowledge about the subject, but you likely couldn't cast a spell targeting a different creature. This condition ends if a creature uses hostile actions against you or any of your allies.",
  },
  {
    id: 'b7c14c1b-d7cc-4899-9e0c-b649832f4295',
    name: 'Fatigued',
    type: 'bad',
    value: null,
    hint: "You take a -1 status penalty to AC and saving throws. You can't use exploration activities performed while traveling. You recover from fatigue after a full night's rest.",
  },
  {
    id: '6b33c68c-b0e2-4f77-a5c3-4c626f48d5f7',
    name: 'Off-Guard',
    type: 'bad',
    value: null,
    hint: 'You take a -2 circumstance penalty to AC.',
  },
  {
    id: 'c9d3c8de-31b4-4f09-8f88-11a2e59d0f6d',
    name: 'Fleeing',
    type: 'bad',
    value: null,
    hint: "On your turn, you must spend each of your actions trying to escape the source of the fleeing condition as expediently as possible. You can't Delay or Ready while fleeing.",
  },
  {
    id: 'e6b12a44-88ab-4ef5-bc84-f4f42a6f26b0',
    name: 'Frightened',
    type: 'bad',
    value: 1,
    hint: 'You take a status penalty equal to this value to all your checks and DCs. Unless specified otherwise, at the end of each of your turns, the value of your frightened condition decreases by 1.',
  },
  {
    id: 'a7c9b29b-bef5-4c5d-8b8b-7e65e530a7b8',
    name: 'Persistent Damage',
    type: 'bad',
    value: null,
    hint: 'You are taking damage from an ongoing effect. Instead of taking persistent damage immediately, you take it at the end of each of your turns as long as you have the condition, rolling any damage dice anew each time. After you take persistent damage, roll a DC 15 flat check to see if you recover from the persistent damage. If you succeed, the condition ends.',
  },
  {
    id: 'f1d5b7df-233a-4c0b-8b34-ff20baf42e6d',
    name: 'Prone',
    type: 'bad',
    value: null,
    hint: "You are off-guard and take a -2 circumstance penalty to attack rolls. The only move actions you can use while you're prone are Crawl and Stand. Standing up ends the prone condition. You can Take Cover while prone to hunker down and gain greater cover against ranged attacks, even if you don't have an object to get behind, which grants you a +4 circumstance bonus to AC against ranged attacks (but you remain off-guard).",
  },
  {
    id: '39de0ab3-6b23-4c07-9e63-8c7e8c3b2ab2',
    name: 'Petrified',
    type: 'bad',
    value: null,
    hint: "You can't act, nor can you sense anything. You become an object with a Bulk double your normal Bulk (typically 12 for a petrified Medium creature or 6 for a petrified Small creature), AC 9, Hardness 8, and the same current Hit Points you had when alive. You don't have a Broken Threshold. When the petrified condition ends, you have the same number of Hit Points you had as a statue. If the statue is destroyed, you immediately die. While petrified, your mind and body are in stasis, so you don't age or notice the passing of time.",
  },
  {
    id: '0d11cf5d-ec49-4c0f-9133-5c2bfc2b5a6c',
    name: 'Sickened',
    type: 'bad',
    value: 1,
    hint: "You take a status penalty equal to this value on all your checks and DCs. You can't willingly ingest anything—including elixirs and potions—while sickened. You can spend a single action retching in an attempt to recover, which lets you immediately attempt a Fortitude save against the DC of the effect that made you sickened. On a success, you reduce your sickened value by 1 (or by 2 on a critical success).",
  },
  {
    id: '5e3b6b8b-889e-46e3-b9c5-7c2d8e8e3f3d',
    name: 'Paralyzed',
    type: 'bad',
    value: null,
    hint: "You have the off-guard condition and can't act except to Recall Knowledge and use actions that require only your mind (as determined by the GM). Your senses still function, but only in the areas you can perceive without moving, so you can't Seek.",
  },
  {
    id: '2f3d6f0d-5a3b-4f9d-8e87-8a4b3a0b4e9c',
    name: 'Restrained',
    type: 'bad',
    value: null,
    hint: "You have the off-guard and immobilized conditions, and you can't use any attack or manipulate actions except to attempt to Escape or Force Open your bonds. Restrained overrides grabbed.",
  },
  {
    id: 'e7d2a3b9-6c13-4f39-9a12-39c1f83e9c01',
    name: 'Quickened',
    type: 'good',
    value: null,
    hint: "You gain 1 additional action at the start of your turn each round. Because quickened has its effect at the start of your turn, you don't immediately gain actions if you become quickened during your turn.",
  },
  {
    id: 'f93a47de-0a5f-4f1a-87b3-2b7eac6cf1c2',
    name: 'Invisible',
    type: 'good',
    value: null,
    hint: "You're undetected to everyone. Creatures can Seek to detect you; if a creature succeeds at its Perception check against your Stealth DC, you become hidden to that creature until you Sneak to become undetected again. If you become invisible while someone can already see you, you start out hidden to them (instead of undetected) until you successfully Sneak. You can't become observed while invisible except via special abilities or magic.",
  },
  {
    id: '1b8f6402-2a91-4c6f-9412-4d12d9b37e5a',
    name: 'Hidden',
    type: 'good',
    value: null,
    hint: "While you're hidden from a creature, that creature knows the space you're in but can't tell precisely where you are. You typically become hidden by using Stealth to Hide. When Seeking a creature using only imprecise senses, it remains hidden, rather than observed. A creature you're hidden from is off-guard to you, and it must succeed at a DC 11 flat check when targeting you with an attack, spell, or other effect or it fails to affect you. Area effects aren't subject to this flat check.",
  },
  {
    id: '4e6b29a8-7e42-49a3-8d10-25c6e5b8c03d',
    name: 'Concealed',
    type: 'good',
    value: null,
    hint: "You can be concealed to some creatures but not others. While concealed, you can still be observed, but you're tougher to target. A creature that you're concealed from must succeed at a DC 5 flat check when targeting you with an attack, spell, or other effect. If the check fails, you aren't affected. Area effects aren't subject to this flat check.",
  },
  {
    id: 'a38c1f1c-9b45-4a1e-8cb3-df4e5fbd12a6',
    name: 'Undetected',
    type: 'good',
    value: null,
    hint: "When you are undetected by a creature, that creature can't see you at all, has no idea what space you occupy, and can't target you, though you still can be affected by abilities that target an area. When you're undetected by a creature, that creature is off-guard to you.",
  },
  {
    id: 'd52a7f4f-64e9-4b33-8fb5-83a4f2b0c17e',
    name: 'Unnoticed',
    type: 'good',
    value: null,
    hint: "If you're unnoticed by a creature, that creature has no idea you're present. When you're unnoticed, you're also undetected. This matters for abilities that can be used only against targets totally unaware of your presence.",
  },
  {
    id: '5c2e7b8f-2d7a-4a90-9f8b-8e1d3f9c12a3',
    name: 'Delay',
    type: 'action',
    value: null,
    hint: "The rest of your turn doesn't happen yet. Instead, you're removed from the initiative order. You can return to the initiative order as a free action triggered by the end of any other creature's turn. This permanently changes your initiative to the new position. You can't use reactions until you return to the initiative order. If you Delay an entire round without returning to the initiative order, the actions from the Delayed turn are lost, your initiative doesn't change, and your next turn occurs at your original position in the initiative order.",
  },
  {
    id: '8f7a13b9-4c82-4f2a-bc37-1d4c9a0e5d6f',
    name: 'Ready',
    type: 'action',
    value: null,
    hint: "You prepare to use an action that will occur outside your turn. Choose a single action or free action you can use, and designate a trigger. Your turn then ends. If the trigger you designated occurs before the start of your next turn, you can use the chosen action as a reaction (provided you still meet the requirements to use it). You can't Ready a free action that already has a trigger. If you have a multiple attack penalty and your readied action is an attack action, your readied attack takes the multiple attack penalty you had at the time you used Ready. This is one of the few times the multiple attack penalty applies when it's not your turn.",
  },
];
